"use client";
import { motion } from "framer-motion";
import { Phone, Mail, Globe, MessageCircle, Send } from "lucide-react";
import { useLanguage } from "./LanguageProvider";
import PageAura from "./PageAura";
const copy={
it:{label:"Contatti",title:"Parliamo del tuo prossimo progetto.",intro:"Hai un'idea da sviluppare, vuoi migliorare la tua presenza online oppure desideri una consulenza? Contattami senza impegno.",phone:"Telefono",operation:"Operatività",remote:"Lavoro da remoto in tutta Italia",email:"Invia Email"},
en:{label:"Contact",title:"Let's talk about your next project.",intro:"Do you have an idea to develop, want to improve your online presence or need a consultation? Get in touch with no obligation.",phone:"Phone",operation:"Availability",remote:"I work remotely with clients in Italy and abroad",email:"Send Email"},
es:{label:"Contacto",title:"Hablemos de tu próximo proyecto.",intro:"¿Tienes una idea que desarrollar, quieres mejorar tu presencia online o necesitas una consultoría? Contáctame sin compromiso.",phone:"Teléfono",operation:"Disponibilidad",remote:"Trabajo de forma remota con clientes en Italia y en el extranjero",email:"Enviar Email"}
};
export default function Contact(){const {language}=useLanguage();const t=copy[language];return <section id="contatti" className="relative overflow-hidden bg-black py-28"><PageAura word="CONTACT"/><div className="relative z-10 mx-auto max-w-7xl px-6"><motion.div initial={{opacity:0,y:25}} whileInView={{opacity:1,y:0}} viewport={{once:true}} className="mx-auto max-w-3xl text-center"><span className="text-sm font-semibold uppercase tracking-[4px] text-red-500">{t.label}</span><h2 className="mt-5 text-5xl font-black tracking-[-.04em] text-white md:text-7xl">{t.title}</h2><p className="mt-6 text-lg leading-8 text-zinc-400">{t.intro}</p></motion.div><div className="mt-20 grid items-stretch gap-8 md:grid-cols-3"><div className="wow-card equal-card glass-panel rounded-[32px] p-8 text-center transition hover:-translate-y-2"><Phone className="premium-icon mx-auto mb-6 rounded-xl p-2 text-red-500" size={34}/><h3 className="text-xl font-bold text-white">{t.phone}</h3><p className="mt-4 text-zinc-400">377 599 4493</p></div><div className="wow-card equal-card glass-panel rounded-[32px] p-8 text-center transition hover:-translate-y-2"><Mail className="premium-icon mx-auto mb-6 rounded-xl p-2 text-red-500" size={34}/><h3 className="text-xl font-bold text-white">Email</h3><p className="mt-4 text-zinc-400">info@rpdigital.it</p></div><div className="wow-card equal-card glass-panel rounded-[32px] p-8 text-center transition hover:-translate-y-2"><Globe className="premium-icon mx-auto mb-6 rounded-xl p-2 text-red-500" size={34}/><h3 className="text-xl font-bold text-white">{t.operation}</h3><p className="mt-4 text-zinc-400">{t.remote}</p></div></div><div className="mt-16 flex flex-wrap justify-center gap-5"><a href="https://wa.me/393775994493" target="_blank" rel="noopener noreferrer" className="flex items-center gap-2 rounded-full bg-green-600 px-8 py-4 font-semibold text-white transition hover:scale-105"><MessageCircle size={18}/>WhatsApp</a><a href="mailto:info@rpdigital.it" className="flex items-center gap-2 rounded-full bg-red-600 px-8 py-4 font-semibold text-white shadow-[0_0_35px_rgba(239,32,41,.2)] transition hover:scale-105"><Send size={18}/>{t.email}</a></div></div></section>}
