"use client";
import { motion } from "framer-motion";
import { MessageCircle, Lightbulb, Code2, Rocket } from "lucide-react";
import { useLanguage } from "./LanguageProvider";
const icons=[MessageCircle,Lightbulb,Code2,Rocket];
const copy={
it:{label:"Metodo",title:"Un processo semplice, risultati concreti.",intro:"Ogni progetto segue un percorso chiaro, dalla prima idea fino alla pubblicazione e alla crescita online.",items:[["Ascolto","Analizziamo insieme il tuo progetto, gli obiettivi e il pubblico che vuoi raggiungere."],["Strategia","Progetto la soluzione più efficace per migliorare la tua presenza digitale e ottenere risultati concreti."],["Realizzazione","Sviluppo il sito, l'app o la strategia digitale curando ogni dettaglio, dal design alle prestazioni."],["Crescita","Dopo la pubblicazione continuo a supportarti con ottimizzazioni, aggiornamenti e nuove opportunità."]]},
en:{label:"Method",title:"A simple process, concrete results.",intro:"Every project follows a clear path, from the first idea through launch and online growth.",items:[["Listen","Together we analyze your project, goals and the audience you want to reach."],["Strategy","I design the most effective solution to improve your digital presence and achieve concrete results."],["Creation","I develop the website, app or digital strategy, taking care of every detail from design to performance."],["Growth","After launch, I continue supporting you with optimizations, updates and new opportunities."]]},
es:{label:"Método",title:"Un proceso sencillo, resultados concretos.",intro:"Cada proyecto sigue un recorrido claro, desde la primera idea hasta la publicación y el crecimiento online.",items:[["Escucha","Analizamos juntos tu proyecto, los objetivos y el público al que quieres llegar."],["Estrategia","Diseño la solución más eficaz para mejorar tu presencia digital y conseguir resultados concretos."],["Realización","Desarrollo el sitio, la app o la estrategia digital cuidando cada detalle, desde el diseño hasta el rendimiento."],["Crecimiento","Después de la publicación sigo apoyándote con optimizaciones, actualizaciones y nuevas oportunidades."]]}
};
export default function Process(){const {language}=useLanguage();const t=copy[language];return <section id="metodo" className="relative overflow-hidden bg-[#050505] py-28"><div className="mx-auto max-w-7xl px-6"><div className="mx-auto mb-20 max-w-3xl text-center"><span className="text-sm font-semibold uppercase tracking-[4px] text-red-500">{t.label}</span><h2 className="mt-5 text-5xl font-black tracking-[-.04em] text-white md:text-7xl">{t.title}</h2><p className="mt-6 text-lg leading-8 text-zinc-400">{t.intro}</p></div><div className="grid gap-8 md:grid-cols-2 xl:grid-cols-4">{t.items.map((item,i)=>{const Icon=icons[i];return <motion.div key={i} whileHover={{y:-8}} className="wow-card glass-panel group relative rounded-[32px] p-8"><span className="display-outline absolute right-6 top-4 text-6xl font-black">0{i+1}</span><div className="mb-8 flex h-16 w-16 items-center justify-center rounded-2xl bg-red-600/15"><Icon size={30} className="text-red-500"/></div><h3 className="mb-4 text-2xl font-bold text-white">{item[0]}</h3><p className="leading-8 text-zinc-400">{item[1]}</p></motion.div>})}</div></div></section>}
