"use client";
import { motion } from "framer-motion";
import { Globe, Smartphone, Bot, Search, Megaphone, MonitorSmartphone } from "lucide-react";
import { useLanguage } from "./LanguageProvider";
const icons=[Globe,Smartphone,Bot,MonitorSmartphone,Search,Megaphone];
const copy={
it:{label:"Servizi",title:"Soluzioni digitali per far crescere il tuo business.",intro:"Ogni progetto nasce con un obiettivo preciso: creare strumenti digitali efficaci, moderni e orientati ai risultati.",items:[["Siti Web","Siti vetrina, e-commerce e landing page moderne, veloci e ottimizzate per convertire visitatori in clienti."],["Social Media","Strategie, contenuti e gestione professionale di Facebook, Instagram, LinkedIn e TikTok."],["AI & Automazioni","Chatbot intelligenti, workflow automatici e integrazioni per farti risparmiare tempo ogni giorno."],["App","Applicazioni mobile e web app per aziende, professionisti e attività locali."],["SEO","Ottimizzazione tecnica e strategica per aumentare la visibilità su Google."],["Advertising","Campagne Meta e Google Ads progettate per generare contatti e vendite."]]},
en:{label:"Services",title:"Digital solutions to grow your business.",intro:"Every project starts with a clear goal: creating effective, modern digital tools focused on measurable results.",items:[["Websites","Modern, fast and conversion-focused corporate websites, e-commerce stores and landing pages."],["Social Media","Professional strategies, content and management for Facebook, Instagram, LinkedIn and TikTok."],["AI & Automation","Smart chatbots, automated workflows and integrations designed to save you time every day."],["Apps","Mobile applications and web apps for companies, professionals and local businesses."],["SEO","Technical and strategic optimization to increase your visibility on Google."],["Advertising","Meta and Google Ads campaigns designed to generate leads and sales."]]},
es:{label:"Servicios",title:"Soluciones digitales para hacer crecer tu negocio.",intro:"Cada proyecto nace con un objetivo claro: crear herramientas digitales eficaces, modernas y orientadas a resultados.",items:[["Sitios Web","Sitios corporativos, e-commerce y landing pages modernas, rápidas y optimizadas para convertir visitas en clientes."],["Redes Sociales","Estrategias, contenidos y gestión profesional de Facebook, Instagram, LinkedIn y TikTok."],["IA y Automatización","Chatbots inteligentes, flujos automáticos e integraciones para ahorrar tiempo cada día."],["Apps","Aplicaciones móviles y web apps para empresas, profesionales y negocios locales."],["SEO","Optimización técnica y estratégica para aumentar la visibilidad en Google."],["Publicidad","Campañas de Meta y Google Ads diseñadas para generar contactos y ventas."]]}
};
export default function Services(){const {language}=useLanguage();const t=copy[language];return <section id="servizi" className="relative bg-black py-28"><div className="mx-auto max-w-7xl px-6"><motion.div initial={{opacity:0,y:25}} whileInView={{opacity:1,y:0}} viewport={{once:true}} className="mx-auto mb-20 max-w-3xl text-center"><span className="text-sm font-semibold uppercase tracking-[4px] text-red-500">{t.label}</span><h2 className="mt-5 text-4xl font-black text-white md:text-5xl">{t.title}</h2><p className="mt-6 text-lg leading-8 text-zinc-400">{t.intro}</p></motion.div><div className="grid gap-8 md:grid-cols-2 lg:grid-cols-3">{t.items.map((item,i)=>{const Icon=icons[i];return <motion.div key={item[0]} initial={{opacity:0,y:35}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.06}} className="rounded-3xl border border-white/10 bg-white/5 p-8 transition hover:-translate-y-2 hover:border-red-500/40"><div className="mb-6 flex h-14 w-14 items-center justify-center rounded-2xl bg-red-600/15"><Icon className="text-red-500" size={28}/></div><h3 className="text-2xl font-bold text-white">{item[0]}</h3><p className="mt-4 leading-8 text-zinc-400">{item[1]}</p></motion.div>})}</div></div></section>}
